<?php

// Created by using the following query and cleaned up / removed duplicates manually
// SELECT `template`, 
// SUBSTR(`template` FROM 1 + POSITION(':' IN `template`)) as `suffix`,
// COUNT(*) AS `count` 
// FROM `verbs` 
// GROUP BY `template`
// ORDER BY CHAR_LENGTH(`suffix`) DESC, 
// REVERSE(`suffix`) DESC, 
// `count` DESC

class VerbLists {

    static $AdHoc = array(
        array('template' => 'promouvoir', 'suffix' => 'ouvoir'),
        array('template' => 'pleuvoir', 'suffix' => 'euvoir'),
        array('template' => 'décevoir', 'suffix' => 'cevoir'),
        # array('template' => 'ravoir','suffix' => 'ravoir'), // Exclu car c'est un verbe déféctif. 
        array('template' => 'vouloir', 'suffix' => 'ouloir'),
        array('template' => 'sourdre', 'suffix' => 'ourdre'),
        array('template' => 'mourir', 'suffix' => 'ourir'),
        array('template' => 'fleurir', 'suffix' => 'eurir'),
        array('template' => 'devoir', 'suffix' => 'evoir'),
        array('template' => 'savoir', 'suffix' => 'avoir'),
        array('template' => 'apparoir', 'suffix' => 'aroir'),
        array('template' => 'falloir', 'suffix' => 'lloir'),
        array('template' => 'bouillir', 'suffix' => 'illir'),
        array('template' => 'disséquer', 'suffix' => 'équer'),
        array('template' => 'léguer', 'suffix' => 'éguer'),
        array('template' => 'enfiévrer', 'suffix' => 'évrer'),
        array('template' => 'impétrer', 'suffix' => 'étrer'),
        array('template' => 'intégrer', 'suffix' => 'égrer'),
        array('template' => 'exécrer', 'suffix' => 'écrer'),
        array('template' => 'célébrer', 'suffix' => 'ébrer'),
        array('template' => 'régner', 'suffix' => 'égner'),
        # array('template' => 'aller','suffix' => 'aller'), // Exclu, car c'est inutile
        array('template' => 'régler', 'suffix' => 'égler'),
        array('template' => 'sécher', 'suffix' => 'écher'),
        array('template' => 'mettre', 'suffix' => 'ettre'),
        array('template' => 'croître', 'suffix' => 'oître'),
        array('template' => 'repaître', 'suffix' => 'aître'),
        array('template' => 'prendre', 'suffix' => 'endre'),
        array('template' => 'gésir', 'suffix' => 'ésir'),
        array('template' => 'quérir', 'suffix' => 'érir'),
        array('template' => 'valoir', 'suffix' => 'loir'),
        array('template' => 'seoir', 'suffix' => 'eoir'),
        array('template' => 'tenir', 'suffix' => 'enir'),
        array('template' => 'envoyer', 'suffix' => 'oyer'),
        array('template' => 'lever', 'suffix' => 'ever'),
        array('template' => 'jeter', 'suffix' => 'eter'),
        array('template' => 'décréter', 'suffix' => 'éter'),
        array('template' => 'léser', 'suffix' => 'éser'),
        array('template' => 'peser', 'suffix' => 'eser'),
        array('template' => 'référer', 'suffix' => 'érer'),
        array('template' => 'receper', 'suffix' => 'eper'),
        array('template' => 'mener', 'suffix' => 'ener'),
        array('template' => 'aliéner', 'suffix' => 'éner'),
        array('template' => 'semer', 'suffix' => 'emer'),
        array('template' => 'crémer', 'suffix' => 'émer'),
        array('template' => 'appeler', 'suffix' => 'eler'),
        array('template' => 'révéler', 'suffix' => 'éler'),
        array('template' => 'abréger', 'suffix' => 'éger'),
        array('template' => 'céder', 'suffix' => 'éder'),
        array('template' => 'dépecer', 'suffix' => 'ecer'),
        # array('template' => 'vivre','suffix' => 'ivre'),
        # array('template' => 'être','suffix' => 'être'),// Exclu
        array('template' => 'boire', 'suffix' => 'oire'),
        array('template' => 'faire', 'suffix' => 'aire'),
        array('template' => 'dissoudre', 'suffix' => 'udre'),
        array('template' => 'résoudre', 'suffix' => 'udre'),
        array('template' => 'craindre', 'suffix' => 'ndre'),
        array('template' => 'servir', 'suffix' => 'vir'),
        array('template' => 'ouïr', 'suffix' => 'uïr'),
        array('template' => 'mentir', 'suffix' => 'tir'),
        # array('template' => 'ouvrir','suffix' => 'rir'),
        array('template' => 'voir', 'suffix' => 'oir'),
        # array('template' => 'dormir','suffix' => 'mir'),
        array('template' => 'nettoyer', 'suffix' => 'yer'),
        array('template' => 'manger', 'suffix' => 'ger'),
        array('template' => 'placer', 'suffix' => 'cer'),
        array('template' => 'suivre', 'suffix' => 'vre'),
        array('template' => 'inclure', 'suffix' => 'ure'),
        array('template' => 'battre', 'suffix' => 'tre'),
        array('template' => 'rompre', 'suffix' => 'pre'),
        # array('template' => 'clore','suffix' => 'ore'),
        # array('template' => 'extraire', 'suffix' => 'ire'),
        array('template' => 'tendre', 'suffix' => 'dre'),
        array('template' => 'vaincre', 'suffix' => 'cre'),
        array('template' => 'finir', 'suffix' => 'ir'),
        array('template' => 'aimer', 'suffix' => 'er'),
        array('template' => 'conduire', 'suffix' => 're')
    );
    
    static $VerbesCommuns =
            array("abandonner", "accepter", "accompagner", "acheter",
                "adorer", "agir", "aider", "aimer", "aller", "amener",
                "amuser", "appartenir", "appeler", "apporter", "apprendre",
                "approcher", "apprécier", "arranger", "arriver", "arrêter",
                "asseoir", "assurer", "attaquer", "attendre", "attraper",
                "avancer", "avoir", "baiser", "battre", "blesser", "boire",
                "bosser", "bouger", "brûler", "cacher", "calmer", "casser",
                "cesser", "changer", "chanter", "charger", "chercher", "chier",
                "choisir", "commencer", "comprendre", "compter", "conduire",
                "connaître", "construire", "continuer", "coucher", "couper",
                "courir", "couvrir", "coûter", "craindre", "crever", "crier",
                "croire", "créer", "danser", "demander", "descendre", "devenir",
                "deviner", "devoir", "dire", "diriger", "discuter", "disparaître",
                "donner", "dormir", "douter", "durer", "décider", "découvrir", "défendre",
                "dégager", "dépêcher", "déranger", "désirer", "désoler", "détester",
                "détruire", "dîner", "échapper", "écouter", "écrire", "embrasser",
                "emmener", "emporter", "empêcher", "enfuir", "engager", "enlever",
                "entendre", "entrer", "envoyer", "épouser", "espérer", "essayer",
                "être", "étudier", "éviter", "excuser", "exister", "expliquer",
                "faire", "falloir", "fatiguer", "fermer", "ficher", "filer", "finir",
                "forcer", "foutre", "frapper", "fuir", "fumer", "gagner", "garder",
                "grandir", "habiter", "ignorer", "imaginer", "importer", "inquiéter",
                "installer", "intéresser", "inviter", "jeter", "jouer", "jurer",
                "laisser", "lancer", "laver", "lever", "libérer", "lire", "lâcher",
                "maintenir", "manger", "manquer", "marcher", "marier", "mener",
                "mentir", "mettre", "monter", "montrer", "moquer", "mourir",
                "mériter", "naître", "obliger", "obtenir", "occuper", "offrir",
                "oser", "oublier", "ouvrir", "paraître", "pardonner", "parier",
                "parler", "partager", "partir", "passer", "payer", "penser", "perdre",
                "permettre", "plaire", "plaisanter", "pleuvoir", "porter", "poser",
                "poursuivre", "pousser", "pouvoir", "prendre", "prier", "profiter",
                "promettre", "proposer", "protéger", "prouver", "préférer", "préparer",
                "présenter", "prévenir", "prévoir", "quitter", "raconter", "ramener",
                "rappeler", "rater", "ravir", "recevoir", "recommencer", "reconnaître",
                "refuser", "regarder", "regretter", "rejoindre", "remarquer", "remercier",
                "remettre", "remonter", "rencontrer", "rendre", "rentrer", "reposer",
                "reprendre", "respecter", "respirer", "ressentir", "ressembler", "rester",
                "retenir", "retirer", "retourner", "retrouver", "revenir", "revoir", "rire",
                "risquer", "réaliser", "récupérer", "réfléchir", "régler", "réparer",
                "répondre", "répéter", "réussir", "réveiller", "rêver", "sauter",
                "sauver", "savoir", "sembler", "sentir", "servir", "signer", "signifier",
                "sonner", "sortir", "souffrir", "souhaiter", "souvenir", "suffire",
                "suivre", "supposer", "supporter", "surveiller", "séparer", "taire",
                "tenir", "tenter", "terminer", "tirer", "tomber", "toucher", "tourner",
                "traiter", "travailler", "traverser", "traîner", "tromper", "trouver",
                "tuer", "utiliser", "valoir", "vendre", "venir", "virer", "vivre",
                "voir", "voler", "vouloir", "vérifier");
    static $VerbesEtre =
            array("accourir", "advenir", "aller", "amuser", "apparaitre",
                "apparaître", "arriver", "ascendre", "co-naitre", "co-naître",
                "convenir", "descendre", "devenir", "disconvenir", "débeller",
                "démourir", "départir", "entre-venir", "entrer", "intervenir",
                "issir", "magner", "monter", "mourir", "mésadvenir", "mésavenir",
                "mévenir", "naitre", "naître", "obvenir",/* "paraitre", "paraître", */
                "partir", "parvenir", "pourrir", "provenir", "prémourir", "ragaillardir",
                "raller", "re-aller", "reconvenir", "redevenir", "redépartir",
                "remagner", "remourir", "renaitre", "renaître", "rentrer", "reparaitre",
                "reparaître", "repartir", "reparvenir", "repasser", "repourrir",
                "rerentrer", "rerester", "ressortir", "ressouvenir", "rester", "resurvenir",
                "retomber", "retrépasser", "revenir", "réacharner", "réadvenir",
                "réapparaitre", "réapparaître", "réentrer", "réintervenir", "réévanouir",
                "souvenir", "sortir", "souvenir", "stationner", "sur-aller", "suradvenir",
                "survenir", "tomber", "trépasser", "venir", "échoir", "époustoufler");

}