<?php

// Created by using the following query and cleaned up / removed duplicates manually
// SELECT `template`,
// SUBSTR(`template` FROM 1 + POSITION(':' IN `template`)) as `suffix`,
// COUNT(*) AS `count`
// FROM `verbs`
// GROUP BY `template`
// ORDER BY CHAR_LENGTH(`suffix`) DESC,
// REVERSE(`suffix`) DESC,
// `count` DESC

class VerbLists
{
    static $AdHoc = [
        ['template' => 'promouvoir', 'suffix' => 'ouvoir'],
        ['template' => 'pleuvoir', 'suffix' => 'euvoir'],
        ['template' => 'décevoir', 'suffix' => 'cevoir'],
        # array('template' => 'ravoir','suffix' => 'ravoir'), // Exclu car c'est un verbe déféctif.
        ['template' => 'vouloir', 'suffix' => 'ouloir'],
        ['template' => 'sourdre', 'suffix' => 'ourdre'],
        ['template' => 'mourir', 'suffix' => 'ourir'],
        ['template' => 'fleurir', 'suffix' => 'eurir'],
        ['template' => 'devoir', 'suffix' => 'evoir'],
        ['template' => 'savoir', 'suffix' => 'avoir'],
        ['template' => 'apparoir', 'suffix' => 'aroir'],
        ['template' => 'falloir', 'suffix' => 'lloir'],
        # array('template' => 'bouillir', 'suffix' => 'illir'),
        ['template' => 'disséquer', 'suffix' => 'équer'],
        ['template' => 'léguer', 'suffix' => 'éguer'],
        ['template' => 'enfiévrer', 'suffix' => 'évrer'],
        ['template' => 'impétrer', 'suffix' => 'étrer'],
        ['template' => 'intégrer', 'suffix' => 'égrer'],
        ['template' => 'exécrer', 'suffix' => 'écrer'],
        ['template' => 'célébrer', 'suffix' => 'ébrer'],
        ['template' => 'régner', 'suffix' => 'égner'],
        # array('template' => 'aller','suffix' => 'aller'), // Exclu, car c'est inutile
        ['template' => 'régler', 'suffix' => 'égler'],
        ['template' => 'sécher', 'suffix' => 'écher'],
        ['template' => 'mettre', 'suffix' => 'ettre'],
        ['template' => 'croître', 'suffix' => 'oître'],
        ['template' => 'repaître', 'suffix' => 'aître'],
        ['template' => 'prendre', 'suffix' => 'endre'],
        ['template' => 'gésir', 'suffix' => 'ésir'],
        ['template' => 'conquérir', 'suffix' => 'érir'],
        ['template' => 'valoir', 'suffix' => 'loir'],
        ['template' => 'seoir', 'suffix' => 'eoir'],
        ['template' => 'tenir', 'suffix' => 'enir'],
        ['template' => 'envoyer', 'suffix' => 'oyer'],
        ['template' => 'lever', 'suffix' => 'ever'],
        ['template' => 'jeter', 'suffix' => 'eter'],
        ['template' => 'décréter', 'suffix' => 'éter'],
        ['template' => 'léser', 'suffix' => 'éser'],
        ['template' => 'peser', 'suffix' => 'eser'],
        ['template' => 'référer', 'suffix' => 'érer'],
        ['template' => 'receper', 'suffix' => 'eper'],
        ['template' => 'mener', 'suffix' => 'ener'],
        ['template' => 'aliéner', 'suffix' => 'éner'],
        ['template' => 'semer', 'suffix' => 'emer'],
        ['template' => 'crémer', 'suffix' => 'émer'],
        ['template' => 'appeler', 'suffix' => 'eler'],
        ['template' => 'révéler', 'suffix' => 'éler'],
        ['template' => 'abréger', 'suffix' => 'éger'],
        ['template' => 'céder', 'suffix' => 'éder'],
        ['template' => 'dépecer', 'suffix' => 'ecer'],
        # array('template' => 'vivre','suffix' => 'ivre'),
        # array('template' => 'être','suffix' => 'être'),// Exclu
        ['template' => 'boire', 'suffix' => 'oire'],
        ['template' => 'faire', 'suffix' => 'aire'],
        ['template' => 'dissoudre', 'suffix' => 'udre'],
        ['template' => 'résoudre', 'suffix' => 'udre'],
        ['template' => 'craindre', 'suffix' => 'ndre'],
        ['template' => 'battre', 'suffix' => 'ttre'],
        ['template' => 'servir', 'suffix' => 'vir'],
        ['template' => 'ouïr', 'suffix' => 'uïr'],
        ['template' => 'mentir', 'suffix' => 'tir'],
        # array('template' => 'ouvrir','suffix' => 'rir'),
        ['template' => 'voir', 'suffix' => 'oir'],
        # array('template' => 'dormir','suffix' => 'mir'),
        ['template' => 'nettoyer', 'suffix' => 'yer'],
        ['template' => 'manger', 'suffix' => 'ger'],
        ['template' => 'placer', 'suffix' => 'cer'],
        ['template' => 'suivre', 'suffix' => 'vre'],
        ['template' => 'inclure', 'suffix' => 'ure'],
        ['template' => 'foutre', 'suffix' => 'tre'],
        ['template' => 'rompre', 'suffix' => 'pre'],
        # array('template' => 'clore','suffix' => 'ore'),
        # array('template' => 'extraire', 'suffix' => 'ire'),
        ['template' => 'tendre', 'suffix' => 'dre'],
        ['template' => 'vaincre', 'suffix' => 'cre'],
        ['template' => 'finir', 'suffix' => 'ir'],
        ['template' => 'aimer', 'suffix' => 'er'],
        ['template' => 'conduire', 'suffix' => 're'],
    ];

    static $VerbesCommuns = [
        "abandonner",
        "accepter",
        "accompagner",
        "acheter",
        "adorer",
        "agir",
        "aider",
        "aimer",
        "aller",
        "amener",
        "amuser",
        "appartenir",
        "appeler",
        "apporter",
        "apprendre",
        "approcher",
        "apprécier",
        "arranger",
        "arriver",
        "arrêter",
        "asseoir",
        "assurer",
        "attaquer",
        "attendre",
        "attraper",
        "avancer",
        "avoir",
        "baiser",
        "battre",
        "blesser",
        "boire",
        "bosser",
        "bouger",
        "brûler",
        "cacher",
        "calmer",
        "casser",
        "cesser",
        "changer",
        "chanter",
        "charger",
        "chercher",
        "chier",
        "choisir",
        "commencer",
        "comprendre",
        "compter",
        "conduire",
        "connaître",
        "construire",
        "continuer",
        "coucher",
        "couper",
        "courir",
        "couvrir",
        "coûter",
        "craindre",
        "crever",
        "crier",
        "croire",
        "créer",
        "danser",
        "demander",
        "descendre",
        "devenir",
        "deviner",
        "devoir",
        "dire",
        "diriger",
        "discuter",
        "disparaître",
        "donner",
        "dormir",
        "douter",
        "durer",
        "décider",
        "découvrir",
        "défendre",
        "dégager",
        "dépêcher",
        "déranger",
        "désirer",
        "désoler",
        "détester",
        "détruire",
        "dîner",
        "échapper",
        "écouter",
        "écrire",
        "embrasser",
        "emmener",
        "emporter",
        "empêcher",
        "enfuir",
        "engager",
        "enlever",
        "entendre",
        "entrer",
        "envoyer",
        "épouser",
        "espérer",
        "essayer",
        "être",
        "étudier",
        "éviter",
        "excuser",
        "exister",
        "expliquer",
        "faire",
        "falloir",
        "fatiguer",
        "fermer",
        "ficher",
        "filer",
        "finir",
        "forcer",
        "foutre",
        "frapper",
        "fuir",
        "fumer",
        "gagner",
        "garder",
        "grandir",
        "habiter",
        "ignorer",
        "imaginer",
        "importer",
        "inquiéter",
        "installer",
        "intéresser",
        "inviter",
        "jeter",
        "jouer",
        "jurer",
        "laisser",
        "lancer",
        "laver",
        "lever",
        "libérer",
        "lire",
        "lâcher",
        "maintenir",
        "manger",
        "manquer",
        "marcher",
        "marier",
        "mener",
        "mentir",
        "mettre",
        "monter",
        "montrer",
        "moquer",
        "mourir",
        "mériter",
        "naître",
        "obliger",
        "obtenir",
        "occuper",
        "offrir",
        "oser",
        "oublier",
        "ouvrir",
        "paraître",
        "pardonner",
        "parier",
        "parler",
        "partager",
        "partir",
        "passer",
        "payer",
        "penser",
        "perdre",
        "permettre",
        "plaire",
        "plaisanter",
        "pleuvoir",
        "porter",
        "poser",
        "poursuivre",
        "pousser",
        "pouvoir",
        "prendre",
        "prier",
        "profiter",
        "promettre",
        "proposer",
        "protéger",
        "prouver",
        "préférer",
        "préparer",
        "présenter",
        "prévenir",
        "prévoir",
        "quitter",
        "raconter",
        "ramener",
        "rappeler",
        "rater",
        "ravir",
        "recevoir",
        "recommencer",
        "reconnaître",
        "refuser",
        "regarder",
        "regretter",
        "rejoindre",
        "remarquer",
        "remercier",
        "remettre",
        "remonter",
        "rencontrer",
        "rendre",
        "rentrer",
        "reposer",
        "reprendre",
        "respecter",
        "respirer",
        "ressentir",
        "ressembler",
        "rester",
        "retenir",
        "retirer",
        "retourner",
        "retrouver",
        "revenir",
        "revoir",
        "rire",
        "risquer",
        "réaliser",
        "récupérer",
        "réfléchir",
        "régler",
        "réparer",
        "répondre",
        "répéter",
        "réussir",
        "réveiller",
        "rêver",
        "sauter",
        "sauver",
        "savoir",
        "sembler",
        "sentir",
        "servir",
        "signer",
        "signifier",
        "sonner",
        "sortir",
        "souffrir",
        "souhaiter",
        "souvenir",
        "suffire",
        "suivre",
        "supposer",
        "supporter",
        "surveiller",
        "séparer",
        "taire",
        "tenir",
        "tenter",
        "terminer",
        "tirer",
        "tomber",
        "toucher",
        "tourner",
        "traiter",
        "travailler",
        "traverser",
        "traîner",
        "tromper",
        "trouver",
        "tuer",
        "utiliser",
        "valoir",
        "vendre",
        "venir",
        "virer",
        "vivre",
        "voir",
        "voler",
        "vouloir",
        "vérifier",
    ];
    static $VerbesEtre = [
        "accourir",
        "advenir",
        "aller",
        "amuser",
        "apparaitre",
        "apparaître",
        "arriver",
        "ascendre",
        "co-naitre",
        "co-naître",
        "convenir",
        "descendre",
        "devenir",
        "disconvenir",
        "débeller",
        "démourir",
        "départir",
        "entre-venir",
        "entrer",
        "intervenir",
        "issir",
        "magner",
        "monter",
        "mourir",
        "mésadvenir",
        "mésavenir",
        "mévenir",
        "naitre",
        "naître",
        "obvenir" /* "paraitre", "paraître", */,
        "partir",
        "parvenir",
        "pourrir",
        "provenir",
        "prémourir",
        "ragaillardir",
        "raller",
        "re-aller",
        "reconvenir",
        "redevenir",
        "redépartir",
        "remagner",
        "remourir",
        "renaitre",
        "renaître",
        "rentrer",
        "reparaitre",
        "reparaître",
        "repartir",
        "reparvenir",
        "repasser",
        "repourrir",
        "rerentrer",
        "rerester",
        "ressortir",
        "ressouvenir",
        "rester",
        "resurvenir",
        "retomber",
        "retrépasser",
        "revenir",
        "réacharner",
        "réadvenir",
        "réapparaitre",
        "réapparaître",
        "réentrer",
        "réintervenir",
        "réévanouir",
        "souvenir",
        "sortir",
        "souvenir",
        "stationner",
        "sur-aller",
        "suradvenir",
        "survenir",
        "tomber",
        "trépasser",
        "venir",
        "échoir",
        "époustoufler",
    ];
}
